name: CI

# Updated at 2025-07-19T01:27:00Z - Added project installation for tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install -e .
      - name: Run minimal test
        run: python test_minimal.py
      - name: Run basic tests
        run: pytest tests/test_basic.py -v