name: CI

# Updated at 2025-07-19T01:27:00Z - Added project installation for tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      ollama:
        image: ollama/ollama:latest
        ports:
          - 11434:11434
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install -e .
      - name: Run minimal test
        run: python test_minimal.py
      - name: Wait for Ollama
        run: |
          for i in {1..60}; do
            if curl --fail http://localhost:11434/api/version; then
              echo "Ollama is up!"
              break
            fi
            echo "Waiting for Ollama... (attempt $i/60)"
            sleep 10
          done
      - name: Init Ollama model
        run: |
          curl -X POST http://localhost:11434/api/pull -d '{"name": "phi3"}' -H 'Content-Type: application/json'
        env:
          OLLAMA_HOST: localhost
      - name: Run tests
        run: pytest